
import type { Metadata } from "next";
import { Exo } from "next/font/google";
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import "./globals.css";
import Navbar from "@/components/layout/navbar/navbar";
import Footer from "@/components/layout/footer/footer";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import Providers from "@/ServicesUi/Providers";

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.className} antialiased`}
      >
        <Providers>
          <Navbar/>
        <Toaster position="top-right" />
        {children}
        <Footer/>
        </Providers>
      </body>
    </html>
  );
}
